databases:
  - name: portfolio
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    name: portfolio
    plan: Starter  
    runtime: python  
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 1 