databases:
  - name: portfolio
    databaseName: portfolio
    user: portfolio

services:
  - name: web
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "portfolio.settings"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    healthCheckPath: /